create table if not exists public.customer_conversations (
  id bigint generated by default as identity primary key,
  visitor_name text not null,
  visitor_email text not null,
  user_id uuid references auth.users(id) on delete set null,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.customer_conversations(id) on delete cascade,
  sender_type text not null check (sender_type in ('user', 'admin')),
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists customer_conversations_user_id_idx
  on public.customer_conversations (user_id);

create index if not exists customer_conversations_status_idx
  on public.customer_conversations (status);

create index if not exists customer_messages_conversation_id_idx
  on public.customer_messages (conversation_id, created_at);

alter table public.customer_conversations enable row level security;
alter table public.customer_messages enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'customer_conversations' and policyname = 'Anyone can create customer conversations') then
    create policy "Anyone can create customer conversations" on public.customer_conversations for insert with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'customer_conversations' and policyname = 'Authenticated users can read own conversations') then
    create policy "Authenticated users can read own conversations" on public.customer_conversations for select using (auth.uid() = user_id or user_id is null);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'customer_conversations' and policyname = 'Admins can read all customer conversations') then
    create policy "Admins can read all customer conversations" on public.customer_conversations for select using (
      exists (
        select 1 from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
      )
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'customer_conversations' and policyname = 'Authenticated users can update own conversations') then
    create policy "Authenticated users can update own conversations" on public.customer_conversations for update using (auth.uid() = user_id or user_id is null) with check (auth.uid() = user_id or user_id is null);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'customer_conversations' and policyname = 'Admins can update all customer conversations') then
    create policy "Admins can update all customer conversations" on public.customer_conversations for update using (
      exists (
        select 1 from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
      )
    ) with check (
      exists (
        select 1 from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
      )
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'customer_messages' and policyname = 'Anyone can create customer messages') then
    create policy "Anyone can create customer messages" on public.customer_messages for insert with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'customer_messages' and policyname = 'Anyone can read customer messages') then
    create policy "Anyone can read customer messages" on public.customer_messages for select using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'customer_messages' and policyname = 'Authenticated users can update customer messages') then
    create policy "Authenticated users can update customer messages" on public.customer_messages for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
  end if;
end $$;
