create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  avatar_url text,
  role text not null default 'user',
  created_at timestamptz not null default now()
);

alter table public.profiles
  enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'Profiles are readable') then
    create policy "Profiles are readable" on public.profiles for select using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can update own profile') then
    create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can insert own profile') then
    create policy "Users can insert own profile" on public.profiles for insert with check (auth.uid() = id);
  end if;
end $$;

alter table public.reviews
  add column if not exists user_id uuid references auth.users(id) on delete set null;

create index if not exists reviews_user_id_idx
  on public.reviews (user_id);

create table if not exists public.trip_plans (
  id bigint generated by default as identity primary key
);

alter table public.trip_plans
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists trip_type text,
  add column if not exists start_date date,
  add column if not exists category text,
  add column if not exists accommodation text,
  add column if not exists created_at timestamptz not null default now();

create index if not exists trip_plans_user_id_idx
  on public.trip_plans (user_id);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  destination_id bigint not null references public.destinations(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint favorites_user_destination_unique unique (user_id, destination_id)
);

alter table public.favorites
  enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'favorites' and policyname = 'Users can read own favorites') then
    create policy "Users can read own favorites" on public.favorites for select using (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'favorites' and policyname = 'Users can insert own favorites') then
    create policy "Users can insert own favorites" on public.favorites for insert with check (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'favorites' and policyname = 'Users can delete own favorites') then
    create policy "Users can delete own favorites" on public.favorites for delete using (auth.uid() = user_id);
  end if;
end $$;
