create table if not exists public.destination_videos (
  id bigint generated by default as identity primary key,
  destination_id bigint not null references public.destinations(id) on delete cascade,
  title text not null default 'Video destinasi',
  video_url text not null,
  poster_url text,
  caption text,
  provider text not null default 'upload',
  duration_seconds integer,
  "order" integer not null default 0,
  is_featured boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint destination_videos_video_url_not_blank check (length(trim(video_url)) > 0),
  constraint destination_videos_provider_check check (provider in ('upload', 'youtube', 'vimeo', 'external')),
  constraint destination_videos_duration_check check (duration_seconds is null or duration_seconds > 0),
  constraint destination_videos_unique_video_per_destination unique (destination_id, video_url)
);

create index if not exists destination_videos_destination_id_idx
  on public.destination_videos (destination_id);

create index if not exists destination_videos_active_order_idx
  on public.destination_videos (destination_id, is_active, "order");

create unique index if not exists destination_videos_one_featured_per_destination_idx
  on public.destination_videos (destination_id)
  where is_featured = true and is_active = true;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_destination_videos_updated_at on public.destination_videos;

create trigger set_destination_videos_updated_at
before update on public.destination_videos
for each row
execute function public.set_updated_at();

alter table public.destination_videos enable row level security;

drop policy if exists "Allow public read active destination videos" on public.destination_videos;
drop policy if exists "Allow authenticated insert destination videos" on public.destination_videos;
drop policy if exists "Allow authenticated update destination videos" on public.destination_videos;
drop policy if exists "Allow authenticated delete destination videos" on public.destination_videos;

create policy "Allow public read active destination videos"
on public.destination_videos
for select
to anon, authenticated
using (is_active = true);

create policy "Allow authenticated insert destination videos"
on public.destination_videos
for insert
to authenticated
with check (true);

create policy "Allow authenticated update destination videos"
on public.destination_videos
for update
to authenticated
using (true)
with check (true);

create policy "Allow authenticated delete destination videos"
on public.destination_videos
for delete
to authenticated
using (true);

grant select on public.destination_videos to anon;
grant select, insert, update, delete on public.destination_videos to authenticated;
grant usage, select on sequence public.destination_videos_id_seq to authenticated;
